name: Build & Push Images to ECR + Update YAML

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # 4️⃣ Create ECR repositories if they don't exist
      - name: Create ECR Repositories
        run: |
          for repo in registry-backend registry-frontend registry; do
            aws ecr describe-repositories --repository-names $repo >/dev/null 2>&1 || \
            aws ecr create-repository --repository-name $repo
          done

      # 5️⃣ Set image tag (short SHA)
      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 6️⃣ Build & Push Backend Image
      - name: Build & Push Backend Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/registry-backend
          docker build -t registry-backend ./backend
          docker tag registry-backend $IMAGE_URI:${IMAGE_TAG}
          docker push $IMAGE_URI:${IMAGE_TAG}

      # 7️⃣ Build & Push Frontend Image
      - name: Build & Push Frontend Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/registry-frontend
          docker build -t registry-frontend ./frontend
          docker tag registry-frontend $IMAGE_URI:${IMAGE_TAG}
          docker push $IMAGE_URI:${IMAGE_TAG}

      # 8️⃣ Build & Push Registry Image
      - name: Build & Push Registry Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/registry
          docker build -t registry ./backend  # Or path to your registry Dockerfile if custom
          docker tag registry $IMAGE_URI:${IMAGE_TAG}
          docker push $IMAGE_URI:${IMAGE_TAG}

      # 9️⃣ Update Kubernetes YAML files with new image tags
      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|\(registry-backend:\).*|\1${IMAGE_TAG}|g" k8files/backend.yml
          sed -i "s|\(registry-frontend:\).*|\1${IMAGE_TAG}|g" k8files/frontend.yml
          sed -i "s|\(registry:\).*|\1${IMAGE_TAG}|g" k8files/registry.yml

      # 🔟 Commit and push updated YAMLs
      - name: Commit and Push Updated YAMLs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8files/*.yml
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update image tags to ${IMAGE_TAG}"
          git push
