apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: registry
type: Opaque
stringData:
  DB_USER: registry
  DB_PASS: registry123
  DB_NAME: registry
  JWT_SECRET: 2168e78adafca76a0566f8abcd0ed1ab5534baf24311088ee0ecee437869474a
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: registry
type: Opaque
stringData:
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: admin123
