apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/registry-backend:f9d7904
          ports:
            - containerPort: 6500
          env:
            # ConfigMap values
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: HOST
            - name: REGISTRY_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REGISTRY_PUBLIC_URL
            - name: REGISTRY_CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REGISTRY_CONTAINER_NAME
            # Secret values
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_NAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: registry
spec:
  selector:
    app: backend
  ports:
    - port: 6500
      targetPort: 6500
  type: ClusterIP
