apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/registry-frontend:720c132
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: http://34.202.165.71:6500
            - name: PROXY_TARGET
              value: http://backend:6500
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: registry
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
  type: LoadBalancer
