apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/registry:8b3fa94
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_AUTH
              value: token
            - name: REGISTRY_AUTH_TOKEN_REALM
              value: http://34.202.165.71:6500/api/auth
            - name: REGISTRY_AUTH_TOKEN_SERVICE
              value: registry
            - name: REGISTRY_AUTH_TOKEN_ISSUER
              value: my-auth-server
            - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
              value: /auth/auth.cert
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
            - name: certs
              mountPath: /auth
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pvc
        - name: certs
          hostPath:
            path: ./backend/certs   # Replace with Secret in production
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
